name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install AWS CLI Using Pip
        run: |
          python -m pip install --upgrade pip
          pip install awscli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug Directory Structure
        run: ls -la

      - name: Check and Move to Project Directory
        run: |
          if [ -f "lambda-project/pom.xml" ]; then
            echo "pom.xml found in lambda-project, moving into directory..."
            cd lambda-project
          else
            echo "ERROR: pom.xml not found!"
            exit 1
          fi

      - name: Build and Package Lambda
        run: |
          cd lambda-project
          mvn clean package
          cp target/*.jar ../lambda.zip # Move output to repo root

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name skeleton-lambda-ci --zip-file fileb://lambda.zip
